version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    networks:
      - library-network

  ride-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8082:8083"
    networks:
      - library-network

  chat-service:
    build:
      context: ./lend-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    networks:
      - library-network

  postgres:
    build: .
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lms_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
